# Fetches Cormorant Garamond (serif) + Manrope (sans) latin/latin-ext woff2 subsets
# from Google Fonts and generates a self-contained local fonts.css.
$ErrorActionPreference = 'Stop'
$out = 'assets/fonts'
New-Item -ItemType Directory -Force -Path $out | Out-Null

$ua = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0 Safari/537.36'
$url = 'https://fonts.googleapis.com/css2?family=Cormorant+Garamond:ital,wght@0,300;0,400;0,500;0,600;0,700;1,300;1,400;1,500;1,600&family=Manrope:wght@200;300;400;500;600;700&display=swap'
curl.exe -s -A $ua -o "$out\google.css" $url
$css = Get-Content -Raw "$out\google.css"

$blocks = [regex]::Split($css, '(?=@font-face)')
$merged = @{}     # key -> { latin_url, latin_ext_url, family, style, weight }

foreach ($b in $blocks) {
  if ($b -notmatch '@font-face') { continue }
  if ($b -notmatch 'U\+0000-00FF' -and $b -notmatch 'U\+0100-024F') { continue }
  if ($b -notmatch "font-family:\s*'([^']+)'") { continue }
  $family = $Matches[1]
  $style  = if ($b -match 'font-style:\s*(\w+)') { $Matches[1] } else { 'normal' }
  $weight = if ($b -match 'font-weight:\s*(\d+)') { $Matches[1] } else { '400' }
  if ($b -notmatch 'url\((https://[^)]+\.woff2)\)') { continue }
  $u = $Matches[1]
  $key = "$family|$style|$weight"
  if (-not $merged.ContainsKey($key)) {
    $merged[$key] = [pscustomobject]@{ family = $family; style = $style; weight = $weight; latin = ''; latin_ext = '' }
  }
  if ($b -match 'U\+0000-00FF') { $merged[$key].latin = $u } else { $merged[$key].latin_ext = $u }
}

$prefix = @{ 'Cormorant Garamond' = 'cormorant'; 'Manrope' = 'manrope' }
$rules = @()
foreach ($key in $merged.Keys) {
  $m = $merged[$key]
  $name = $prefix[$m.family]
  $it = if ($m.style -eq 'italic') { 'i' } else { '' }
  $stem = "$name-$($m.weight)$it"
  $dest = Join-Path $out "$stem.woff2"
  if ($m.latin) {
    if (-not (Test-Path $dest) -or (Get-Item $dest).Size -lt 1000) {
      curl.exe -sL -A $ua -o $dest $m.latin
    }
  }
  $srcs = @()
  if ($m.latin) { $srcs += "        url('$stem.woff2') format('woff2');" }
  if ($m.latin_ext) {
    $destE = Join-Path $out "$stem-ext.woff2"
    if (-not (Test-Path $destE) -or (Get-Item $destE).Size -lt 1000) {
      curl.exe -sL -A $ua -o $destE $m.latin_ext
    }
    $srcs += "        url('$stem-ext.woff2') format('woff2');"
  }
  if (-not $srcs) { continue }
  $rules += @"
@font-face {
    font-family: '$($m.family)';
    font-style: $($m.style);
    font-weight: $($m.weight);
    font-display: swap;
    src: $($srcs -join "`n")
}
"@
}

$cssOut = @"
/* Generated by scripts/fetch-fonts.ps1 - local subsets of
   Cormorant Garamond & Manrope (Google Fonts, SIL OFL 1.1). */
$($rules -join "`n")
"@
Set-Content -Path (Join-Path $out 'fonts.css') -Value $cssOut -Encoding utf8
Remove-Item "$out\google.css" -ErrorAction SilentlyContinue
Write-Host "Fonts written:" (Get-ChildItem $out).Count "files"